# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ndl_tei',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/ndl_tei',
                'lib_path': 'ndl_tei'},
  'syms': { 'ndl_tei.core': { 'ndl_tei.core.Client': ('core.html#client', 'ndl_tei/core.py'),
                              'ndl_tei.core.Client.__init__': ('core.html#client.__init__', 'ndl_tei/core.py'),
                              'ndl_tei.core.Client.convert': ('core.html#client.convert', 'ndl_tei/core.py'),
                              'ndl_tei.core.Client.prettify': ('core.html#client.prettify', 'ndl_tei/core.py')}}}
